# gcloud builds submit --config=cloudbuild.yaml .
steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: ['view.sh', '$PROJECT_ID', '${_SQL_FILE}']
timeout: 1200s
substitutions:
  _SQL_FILE: none
serviceAccount: 'projects/$PROJECT_ID/serviceAccounts/bq-views-sa@gcp-solution-dev.iam.gserviceaccount.com'
options:
    substitution_option: 'ALLOW_LOOSE'